indent-size: 2
line-length: 150
force-trailing-newline: true
sort-imports: true
line-breaks: []
extensions:
  - TupleSections
  - BangPatterns
  - OverloadedStrings
  - InstanceSigs
  - LambdaCase
  - DeriveGeneric